# Generated by Django 3.0.8 on 2020-10-20 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoronaWars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('select_plantilla', models.CharField(choices=[('A', 'Model A'), ('B', 'Model B'), ('C', 'Model C')], default='B', max_length=2)),
                ('image_1', models.ImageField(null=True, upload_to='pics')),
                ('image_2', models.ImageField(null=True, upload_to='pics')),
                ('image_3', models.ImageField(blank=True, help_text='Only necessary for models A y B', null=True, upload_to='pics')),
                ('image_4', models.ImageField(blank=True, help_text='Only necessary for model B', null=True, upload_to='pics')),
                ('image_5', models.ImageField(blank=True, help_text='Only necessary for models B y C', null=True, upload_to='pics')),
                ('image_6', models.ImageField(blank=True, help_text='Only necessary for model C', null=True, upload_to='pics')),
            ],
        ),
        migrations.CreateModel(
            name='Developer_Team_Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pics')),
                ('title', models.CharField(max_length=30)),
                ('subtitle', models.CharField(max_length=70)),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Info_Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_home_1', models.CharField(max_length=30)),
                ('message_home_2', models.CharField(max_length=30)),
                ('desc_home_1', models.CharField(max_length=70)),
                ('desc_home_2', models.CharField(max_length=70)),
                ('button_home', models.CharField(max_length=15)),
                ('image_home', models.ImageField(upload_to='pics')),
                ('home_destination', models.CharField(choices=[('top', 'Home'), ('blog', 'News'), ('featured', 'Developer Team'), ('detailednews', 'Detailed News'), ('project', 'Soul&Spirit'), ('project2', 'CoronaWars'), ('contact', 'Contact')], default='top', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_date', models.IntegerField(help_text="Write as 'ddmmyyyy= Day/Month/Year', example 10052019=10/05/2019")),
                ('news_auto_date', models.DateField(auto_now_add=True)),
                ('news_headline', models.CharField(max_length=70)),
                ('news_body', models.TextField(default='Replace this text for one that has at least 250 characters.', help_text='Minimum of 250 characters and a maximum of 500 characters.')),
                ('news_image', models.ImageField(upload_to='pics')),
                ('news_body_big', models.TextField()),
                ('news_title_big', models.CharField(max_length=30)),
                ('news_subtitle_big', models.CharField(max_length=70)),
                ('news_image_big', models.ImageField(upload_to='pics')),
            ],
        ),
        migrations.CreateModel(
            name='SoulAndSpirit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('select_plantilla', models.CharField(choices=[('A', 'Model A'), ('B', 'Model B'), ('C', 'Model C')], default='B', max_length=2)),
                ('image_1', models.ImageField(null=True, upload_to='pics')),
                ('image_2', models.ImageField(null=True, upload_to='pics')),
                ('image_3', models.ImageField(blank=True, help_text='Only necessary for models A y B', null=True, upload_to='pics')),
                ('image_4', models.ImageField(blank=True, help_text='Only necessary for model B', null=True, upload_to='pics')),
                ('image_5', models.ImageField(blank=True, help_text='Only necessary for models B y C', null=True, upload_to='pics')),
                ('image_6', models.ImageField(blank=True, help_text='Only necessary for model C', null=True, upload_to='pics')),
            ],
        ),
    ]
