# Generated by Django 3.0.8 on 2020-11-30 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0002_auto_20201130_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soulandspirit',
            name='image_1_big',
        ),
        migrations.RemoveField(
            model_name='soulandspirit',
            name='image_2_big',
        ),
        migrations.RemoveField(
            model_name='soulandspirit',
            name='image_3_big',
        ),
        migrations.RemoveField(
            model_name='soulandspirit',
            name='image_4_big',
        ),
        migrations.RemoveField(
            model_name='soulandspirit',
            name='image_5_big',
        ),
        migrations.RemoveField(
            model_name='soulandspirit',
            name='image_6_big',
        ),
    ]
