# Generated by Django 3.0.8 on 2020-11-30 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0003_auto_20201130_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='soulandspirit',
            name='image_1_crop',
            field=models.ImageField(null=True, upload_to='pics'),
        ),
        migrations.AddField(
            model_name='soulandspirit',
            name='image_2_crop',
            field=models.ImageField(null=True, upload_to='pics'),
        ),
        migrations.AddField(
            model_name='soulandspirit',
            name='image_3_crop',
            field=models.ImageField(blank=True, help_text='Only necessary for models A y B', null=True, upload_to='pics'),
        ),
        migrations.AddField(
            model_name='soulandspirit',
            name='image_4_crop',
            field=models.ImageField(blank=True, help_text='Only necessary for model B', null=True, upload_to='pics'),
        ),
        migrations.AddField(
            model_name='soulandspirit',
            name='image_5_crop',
            field=models.ImageField(blank=True, help_text='Only necessary for models B y C', null=True, upload_to='pics'),
        ),
        migrations.AddField(
            model_name='soulandspirit',
            name='image_6_crop',
            field=models.ImageField(blank=True, help_text='Only necessary for model C', null=True, upload_to='pics'),
        ),
    ]
