# Generated by Django 3.0.8 on 2020-11-30 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0004_auto_20201130_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soulandspirit',
            name='image_1_crop',
        ),
        migrations.RemoveField(
            model_name='soulandspirit',
            name='image_2_crop',
        ),
        migrations.RemoveField(
            model_name='soulandspirit',
            name='image_3_crop',
        ),
        migrations.RemoveField(
            model_name='soulandspirit',
            name='image_4_crop',
        ),
        migrations.RemoveField(
            model_name='soulandspirit',
            name='image_5_crop',
        ),
        migrations.RemoveField(
            model_name='soulandspirit',
            name='image_6_crop',
        ),
    ]
