# Generated by Django 3.0.8 on 2020-11-30 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0005_auto_20201130_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='soulandspirit',
            name='image_1_big',
            field=models.ImageField(null=True, upload_to='pics'),
        ),
    ]
