# Generated by Django 3.0.8 on 2020-12-02 00:37

from django.db import migrations, models
import test1.models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0009_auto_20201201_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coronawars',
            name='image_2_big',
            field=models.ImageField(null=True, storage=test1.models.OverwriteStorage(), upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='coronawars',
            name='image_3_big',
            field=models.ImageField(blank=True, null=True, storage=test1.models.OverwriteStorage(), upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='coronawars',
            name='image_4_big',
            field=models.ImageField(blank=True, null=True, storage=test1.models.OverwriteStorage(), upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='coronawars',
            name='image_5_big',
            field=models.ImageField(blank=True, null=True, storage=test1.models.OverwriteStorage(), upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='coronawars',
            name='image_6_big',
            field=models.ImageField(blank=True, null=True, storage=test1.models.OverwriteStorage(), upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='soulandspirit',
            name='image_1',
            field=models.ImageField(null=True, storage=test1.models.OverwriteStorage(), upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='soulandspirit',
            name='image_1_big',
            field=models.ImageField(null=True, storage=test1.models.OverwriteStorage(), upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='soulandspirit',
            name='image_2',
            field=models.ImageField(null=True, storage=test1.models.OverwriteStorage(), upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='soulandspirit',
            name='image_2_big',
            field=models.ImageField(null=True, storage=test1.models.OverwriteStorage(), upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='soulandspirit',
            name='image_3',
            field=models.ImageField(blank=True, help_text='Only necessary for models A y B', null=True, storage=test1.models.OverwriteStorage(), upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='soulandspirit',
            name='image_3_big',
            field=models.ImageField(blank=True, null=True, storage=test1.models.OverwriteStorage(), upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='soulandspirit',
            name='image_4',
            field=models.ImageField(blank=True, help_text='Only necessary for model B', null=True, storage=test1.models.OverwriteStorage(), upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='soulandspirit',
            name='image_4_big',
            field=models.ImageField(blank=True, null=True, storage=test1.models.OverwriteStorage(), upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='soulandspirit',
            name='image_5',
            field=models.ImageField(blank=True, help_text='Only necessary for models B y C', null=True, storage=test1.models.OverwriteStorage(), upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='soulandspirit',
            name='image_5_big',
            field=models.ImageField(blank=True, null=True, storage=test1.models.OverwriteStorage(), upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='soulandspirit',
            name='image_6',
            field=models.ImageField(blank=True, help_text='Only necessary for model C', null=True, storage=test1.models.OverwriteStorage(), upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='soulandspirit',
            name='image_6_big',
            field=models.ImageField(blank=True, null=True, storage=test1.models.OverwriteStorage(), upload_to='pics'),
        ),
    ]
