# Generated by Django 3.0.8 on 2020-12-02 19:20

from django.db import migrations, models
import test1.models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0010_auto_20201201_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coronawars',
            name='image_1',
            field=models.ImageField(blank=True, null=True, storage=test1.models.OverwriteStorage(), upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='coronawars',
            name='image_1_big',
            field=models.ImageField(blank=True, null=True, storage=test1.models.OverwriteStorage(), upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='coronawars',
            name='image_2',
            field=models.ImageField(blank=True, null=True, storage=test1.models.OverwriteStorage(), upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='coronawars',
            name='image_2_big',
            field=models.ImageField(blank=True, null=True, storage=test1.models.OverwriteStorage(), upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_image',
            field=models.ImageField(storage=test1.models.OverwriteStorage(), upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_image_big',
            field=models.ImageField(storage=test1.models.OverwriteStorage(), upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='soulandspirit',
            name='image_1',
            field=models.ImageField(blank=True, null=True, storage=test1.models.OverwriteStorage(), upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='soulandspirit',
            name='image_1_big',
            field=models.ImageField(blank=True, null=True, storage=test1.models.OverwriteStorage(), upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='soulandspirit',
            name='image_2',
            field=models.ImageField(blank=True, null=True, storage=test1.models.OverwriteStorage(), upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='soulandspirit',
            name='image_2_big',
            field=models.ImageField(blank=True, null=True, storage=test1.models.OverwriteStorage(), upload_to='pics'),
        ),
    ]
